module.exports = {
    PHONE_AUTH_SUCCESS:"PHONE_AUTH_SUCCESS", 
    PHONE_AUTH_REQUESTED:"PHONE_AUTH_REQUESTED", 
    PHONE_NUM_ERR:"PHONE_NUM_ERR",
    PHONE_CODE_ERR:"PHONE_CODE_ERR",
    PHONE_CODE_SENT:"PHONE_CODE_SENT",
}