module.exports = {
    PHONE_AUTH_SUCCESS:"PHONE_AUTH_SUCCESS", 
    PHONE_AUTH_REQUESTED:"PHONE_AUTH_REQUESTED", 
    PHONE_CODE_ERR:"PHONE_CODE_ERR",
    PHONE_CODE_SENT:"PHONE_CODE_SENT",
    PHONE_AUTH_ERR:"PHONE_AUTH_ERR",
    IMAGE_UPLOAD_REQUESTED: "IMAGE_UPLOAD_REQUESTED",
    IMAGE_UPLOAD_SUCCESS:"IMAGE_UPLOAD_SUCCESS",
    IMAGE_UPLOAD_ERR :"IMAGE_UPLOAD_ERR"
}